secret:
  enabled: true
  nameOverride: {{SECRET_NAME}}
  stringData:
    DATABASE_URL: {{DATABASE_URL}}
    KEYCLOAK_WEBHOOK_SECRET: {{KEYCLOAK_WEBHOOK_SECRET}}
    KEYCLOAK_WEBHOOK_BASIC_USER: {{KEYCLOAK_WEBHOOK_BASIC_USER}}
    KEYCLOAK_WEBHOOK_BASIC_PASS: {{KEYCLOAK_WEBHOOK_BASIC_PASS}}
    SPLUNK_HEC_TOKEN: {{SPLUNK_HEC_TOKEN}}
