replicaCount: 1

configMap:
  data:
    PORT: "4001"
    PROFILE_EVENTS_ENABLED: "true"
    MEDIA_SERVICE_URL: http://svc-media-dev.apps-dev.svc.cluster.local
    MEDIA_CDN_ORIGIN: https://uploads-dev.mereb.app/media-dev
    KAFKA_BROKERS: platform-dev-redpanda-0.platform-dev-redpanda.platform-dev.svc.cluster.local:9092
    KAFKA_SSL: "true"
    KAFKA_SSL_INSECURE: "true"
    OIDC_AUDIENCE: account
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-dev

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
