nameOverride: svc-profile

replicaCount: 1

imagePullSecrets:
  - regcred

image:
  repository: registry.leultewolde.com/mereb/svc-profile
  pullPolicy: Always
  env:
    - name: NODE_ENV
      value: production
    - name: SERVICE_NAME
      value: svc-profile
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-dev.platform-dev.svc.cluster.local:4318
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
      value: http/protobuf
    - name: OIDC_ISSUER
      valueFrom:
        configMapKeyRef:
          name: platform-identity-dev
          key: OIDC_ISSUER
    - name: KEYCLOAK_WEBHOOK_CLIENT_IDS
      valueFrom:
        configMapKeyRef:
          name: platform-identity-dev
          key: KEYCLOAK_WEBHOOK_CLIENT_ID
  envFrom:
    - configMapRef:
        name: svc-profile-dev-config
    - secretRef:
        name: svc-profile-dev-secrets
        optional: true

service:
  ports:
    - name: http
      port: 80
      targetPort: http
      containerPort: 4001

ingress:
  enabled: true
  className: kong
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-http
    konghq.com/strip-path: "true"
  hosts:
    - host: api-dev.mereb.app
      paths:
        - path: /profile
          pathType: Prefix
          servicePort: http
  tls:
    - secretName: profile-dev-tls
      hosts:
        - api-dev.mereb.app

configMap:
  enabled: true
  nameOverride: svc-profile-dev-config
  data:
    PORT: "4001"
    PROFILE_EVENTS_ENABLED: "true"
    MEDIA_SERVICE_URL: http://svc-media-dev.apps-dev.svc.cluster.local
    KAFKA_BROKERS: platform-dev-redpanda-0.platform-dev-redpanda.platform-dev.svc.cluster.local:9092
    KAFKA_SSL: "true"
    KAFKA_SSL_INSECURE: "true"
    OIDC_AUDIENCE: account
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-dev

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
