replicaCount: 1

configMap:
  data:
    PORT: "4001"
    PROFILE_EVENTS_ENABLED: "true"
    MEDIA_SERVICE_URL: http://svc-media-stg.apps-stg.svc.cluster.local
    MEDIA_CDN_ORIGIN: https://uploads-stg.mereb.app/media-stg
    OIDC_AUDIENCE: account
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-stg

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
